Transform: AWS::Serverless-2016-10-31

Description: Publishes content from Salesforce Knowledge to manage-frontend.

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - PROD
      - DEV
    Default: DEV
  AppName:
    Type: String
    Default: manage-help-content-publisher

Conditions:
  IsProd: !Equals [ !Ref Stage, PROD ]

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AppName}-${Stage}
      RetentionInDays: 90

  Lambda:
    Type: AWS::Serverless::Function
    DependsOn: LogGroup
    Properties:
      FunctionName: !Sub ${AppName}-${Stage}
      Handler: managehelpcontentpublisher.Handler::handleRequest
      Runtime: java11
      CodeUri:
        Bucket: support-service-lambdas-dist
        Key: !Sub membership/${Stage}/contact-us-api/contact-us-api.jar
      Timeout: 30
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    DependsOn: Lambda
    Properties:
      Name: !Sub ${AppName}-${Stage}-api-gateway
      StageName: !Sub ${Stage}
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub ${AppName}-${Stage}-usage-plan

  4xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn: ApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub 4XX rate from ${AppName}-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/manage-help-content-publisher/blob/main/README.md#Troubleshooting
        for troubleshooting tips.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub ${AppName}-${Stage}-api-gateway
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: ignore

  5xxApiAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProd
    DependsOn: ApiGateway
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:fulfilment-dev
      AlarmName: !Sub 5XX rate from ${AppName}-${Stage}
      AlarmDescription: >
        See https://github.com/guardian/manage-help-content-publisher/blob/main/README.md#Troubleshooting
        for troubleshooting tips.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub ${AppName}-${Stage}-api-gateway
        - Name: Stage
          Value: !Sub ${Stage}
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 3600
      Statistic: Sum
      Threshold: 1
      TreatMissingData: ignore
